# 2. NumPy

## 2.1. Array creation

In [1]:
import numpy as np

arr_1 = np.array([1, 2, 3, 4, 6])
print(arr_1)
print(type(arr_1))

arr_2 = np.arange(10)
print(arr_2)
print(type(arr_2))

ModuleNotFoundError: No module named 'numpy'

### Evenly spaced numbers over a specified interval

In [ ]:
arr = np.linspace(0, 100, 10)
arr

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## 2.2. Array reshaping

In [ ]:
arr = np.arange(100).reshape(10, 10)
print(arr)
arr.shape

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


(10, 10)

In [ ]:
arr = np.arange(100).reshape(2, 5, 10)
print(arr)
arr.shape

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


(2, 5, 10)

## 2.3. Basic array operations

### Sum

In [ ]:
arr = np.arange(16).reshape(4, 4)
print(arr)

print(arr.sum()) # Sum over all array
print(arr.sum(axis=0)) # Sum over columns
print(arr.sum(axis=1)) # Sum over rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
120
[24 28 32 36]
[ 6 22 38 54]


### Min and Max

In [ ]:
print(arr.max())
print(arr.min())
print(arr.min(axis=1))
print(arr.min(axis=0))

15
0
[ 0  4  8 12]
[0 1 2 3]


### Arrays of ones and zeros

In [ ]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones(10)
arr.mean() # Array mean

1.0

In [ ]:
arr = np.linspace(0, 100, 10)
arr.std() # Array std

31.91423692521127

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 6])
arr_2 = np.arange(5)

np.add(arr_1, arr_2) # Sum of two arrays

array([ 1,  3,  5,  7, 10])

In [ ]:
arr_1 * 5 # Element wise multiplication

array([ 5, 10, 15, 20, 30])

In [ ]:
arr_1 * np.pi

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061, 18.84955592])

In [ ]:
arr_1 ** 5 # Element wise power

array([   1,   32,  243, 1024, 7776], dtype=int32)

In [ ]:
value = 100
np.sqrt(value)

10.0

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 6])
arr_2 = np.arange(5)

arr_1 * arr_2 # Element wise multiplication

array([ 0,  2,  6, 12, 24])

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 6])
arr_2 = np.arange(5)

np.multiply(arr_1, arr_2) # Element wise multiplication

array([ 0,  2,  6, 12, 24])

In [ ]:
arr = [0, np.pi / 2, np.pi / 3, np.pi]
sin_Values = np.sin(arr)

print(f"Input array: {arr} \nSin Values: {sin_Values}")

Input array: [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793] 
Sin Values: [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]


## 2.4. Array manipulation

In [ ]:
arr_1 = np.array([1, 2, 3, 4, 6])
arr_2 = np.arange(5)

print(np.concatenate((arr_1, arr_2), axis=0))
print(np.vstack((arr_1, arr_2)))
print(np.hstack((arr_1, arr_2)))
print(np.column_stack((arr_1, arr_2)))

[1 2 3 4 6 0 1 2 3 4]
[[1 2 3 4 6]
 [0 1 2 3 4]]
[1 2 3 4 6 0 1 2 3 4]
[[1 0]
 [2 1]
 [3 2]
 [4 3]
 [6 4]]


In [ ]:
arr = np.array([11, 2, 13, 4, 16])
print(arr)
print(np.sort(arr))

[11  2 13  4 16]
[ 2  4 11 13 16]


## 2.5. Boolean filtering

In [ ]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
mask = arr >= 13
arr[mask]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
mask_2 = (arr > 13) & (arr < 22)
arr[mask_2]

array([14, 15, 16, 17, 18, 19, 20, 21])

## 2.6. Random arrays

In [ ]:
dice_samples = np.random.randint(1, 7, size=15)
dice_samples

array([4, 3, 1, 6, 4, 4, 6, 6, 3, 3, 1, 6, 6, 2, 5])

In [ ]:
dice_samples = np.random.choice([1, 2, 3, 4, 5, 6], size = 15)
dice_samples

array([1, 2, 1, 1, 6, 5, 1, 6, 4, 2, 1, 1, 4, 1, 4])